name: 'BigLinux Image Action'
description: 'Installs prerequisites for building BigLinux ARM on Ubuntu'
inputs:
  arm-profiles-repo:
    description: 'arm-profiles to clone'
    required: false
    default: 'https://github.com/biglinux/biglinux-arm-profiles'
  device:
    description: 'name of the device the build is for'
    required: true
  edition:
    description: 'name of the profile to build'
    required: true
  branch:
    description: 'stable (default), testing, unstable'
    required: false
    default: stable
  version:
    description: 'image version'
    required: false
    default: "YY.MM"
  overlay-repo:
    description: 'custom overlay repo'
    required: false
  imgtype:
    description: 'image type: normal (default), factory'
    required: false
    default: normal
  img-name:
    description: 'Name for Image'
    required: false
    default: 'BigLinux'
  name:
    description: 'Name for System, User, HostName, and Password.'
    required: false
    default: 'biglinux'
  bigbranch:
    description: 'stable, testing, development'
    required: true
  tmate:
    description: 'run tmate'
    required: false
outputs:
  file-pkg:
    description: "compressed files"
    value: ${{ steps.build.outputs.file-pkg }}
  file-path:
    description: "path of the generated image"
    value: ${{ steps.build.outputs.file-path }}
  file-sha256:
    description: "checksum file for the image"
    value: ${{ steps.build.outputs.file-sha256 }}
  file-torrent:
    description: "torrent file for the image"
    value: ${{ steps.build.outputs.file-torrent }}
  file-signature:
    description: "signature file for the image"
    value: ${{ steps.build.outputs.file-signature }}
runs:
  using: "composite"
  steps:
    - name: Install Build Dependencies
      shell: bash
      run: |
        sudo apt-get update
        sudo apt install -y \
          gdisk zip systemd-container bmap-tools asciidoc \
          libarchive-tools git build-essential cmake \
          libarchive-dev pkg-config libcurl4-openssl-dev \
          libgpgme-dev libssl-dev fakeroot dh-autoreconf \
          qemu-utils qemu-efi-aarch64 qemu-system-arm \
          qemu-user-static mktorrent paperkey gpg \
          ca-certificates u-boot-tools
        sudo pip3 install meson ninja

        # For generic-efi support
        wget http://ports.ubuntu.com/pool/main/g/grub2-unsigned/grub-efi-arm64-bin_2.06-2ubuntu14.1_arm64.deb
        sudo dpkg -x grub-efi-arm64-bin_2.06-2ubuntu14.1_arm64.deb /

    - name: Install Pacman
      shell: bash
      env:
        PACMAN_VERSION: 6.0.2
      run: |
        sudo git clone --depth 1 https://gitlab.manjaro.org/packages/core/pacman.git
        pushd pacman
          sudo wget https://sources.archlinux.org/other/pacman/pacman-${PACMAN_VERSION}.tar.xz
          sudo tar -xvf pacman-${PACMAN_VERSION}.tar.xz
          pushd pacman-${PACMAN_VERSION}
            sudo patch -p1 -i ../pacman-sync-first-option.patch
            sudo meson --prefix=/usr --buildtype=plain -Ddoc=disabled -Ddoxygen=enabled -Dscriptlet-shell=/usr/bin/bash -Dldconfig=/usr/bin/ldconfig build
            sudo meson compile -C build
            sudo meson install -C build
          popd
          sudo install -m644 pacman.conf /etc/pacman.conf
          sudo install -m644 makepkg.conf /etc/
          sudo mkdir -p /etc/pacman.d
          sudo touch /etc/pacman.d/mirrorlist
        popd

    - name: Setup QEMU Binfmt
      shell: bash
      run: |
        sudo wget https://gitlab.manjaro.org/packages/community/manjaro-arm-qemu-static/-/raw/master/qemu-static.conf -O /usr/lib/binfmt.d/qemu-static.conf
        sudo service systemd-binfmt restart

    - name: Install Arch Install Scripts
      shell: bash
      env:
        VERSION: 28
      run: |
        sudo wget https://github.com/archlinux/arch-install-scripts/archive/refs/tags/v${VERSION}.tar.gz -O arch-install-scripts.tar.gz
        sudo tar -xvf arch-install-scripts.tar.gz
        sudo make -C arch-install-scripts-${VERSION}
        sudo make -C arch-install-scripts-${VERSION} check
        sudo make -C arch-install-scripts-${VERSION} PREFIX=/usr install

    - name: Install Manjaro ARM Tools
      shell: bash
      run: |
        sudo git clone https://gitlab.manjaro.org/manjaro-arm/applications/manjaro-arm-tools.git
        install_m_a_tools() {
            pkgname=manjaro-arm-tools
            sudo install -dm777 /usr/share/$pkgname/lib
            sudo install -dm777 /usr/share/$pkgname/profiles
            sudo install -d /etc/$pkgname/
            sudo install -dm777 /var/lib/$pkgname/{pkg,img,tmp,profiles}
            sudo install -dm777 /var/cache/$pkgname/{pkg/pkg-cache,img}
            sudo install -Dm755 $pkgname/lib/* /usr/share/$pkgname/lib/
            sudo install -Dm755 $pkgname/bin/* /usr/bin/
            sudo install -Dm755 $pkgname/lib/manjaro-arm-tools.conf /etc/manjaro-arm-tools/
        }
        install_m_a_tools

        # Remove unnecessary redirections
        sudo sed -i -e 's|1>/dev/null||g' -e 's|1> /dev/null 2>&1||g' -e 's|2>/dev/null||g' /usr/share/manjaro-arm-tools/lib/functions.sh

    - name: Apply BigLinux Changes
      shell: bash
      run: |
        echo "# Change HostName"
        sudo sed -i "s/#HOSTNAME=.*/HOSTNAME='${{ inputs.name }}-arm'/" /etc/manjaro-arm-tools/manjaro-arm-tools.conf
        sudo sed -i "s/#HOSTNAME=.*/HOSTNAME='${{ inputs.name }}-arm'/" /usr/share/manjaro-arm-tools/lib/manjaro-arm-tools.conf
        sudo sed -i "s/HOSTNAME=.*/HOSTNAME='${{ inputs.name }}-arm'/" /usr/share/manjaro-arm-tools/lib/functions.sh

        echo "# Change Image Name"
        sudo sed -i "/IMGNAME=/s/Manjaro/${{ inputs.img-name }}/" /usr/share/manjaro-arm-tools/lib/functions.sh
        sudo sed -i "/IMGNAME=/s/Manjaro/${{ inputs.img-name }}/" /usr/bin/buildarmimg

        echo "# Rootfs"
        echo ${{ github.token }} | gh auth login --with-token
        sed -i 's|wget -q --show-progress --progress=bar:force:noscroll \\||' /usr/share/manjaro-arm-tools/lib/functions.sh
        sed -i 's|https://github.com/manjaro-arm/rootfs.*||' /usr/share/manjaro-arm-tools/lib/functions.sh
        sed -i 's/-O "$ROOTFS_IMG\/Manjaro-ARM-$ARCH-latest.tar.gz".*/gh release -R BigLinux-Package-Build\/build-iso-arm download $(gh release list -R BigLinux-Package-Build\/build-iso-arm | grep rootfs | awk '"'{print $2}'"' | head -n1) -D $ROOTFS_IMG\//' /usr/share/manjaro-arm-tools/lib/functions.sh

        gh release -R BigLinux-Package-Build/build-iso-arm download $(gh release list -R BigLinux-Package-Build/build-iso-arm | grep rootfs | awk '{print $2}' | head -n1)
        cp BigLinux-ARM-aarch64-latest.tar.gz /var/lib/manjaro-arm-tools/img

        sed -i '/bsdtar -xpf/s/Manjaro/BigLinux/' /usr/share/manjaro-arm-tools/lib/functions.sh
        sed -i 's/Manjaro-ARM-$ARCH-latest.tar.gz/BigLinux-ARM-aarch64-latest.tar.gz/' /usr/share/manjaro-arm-tools/lib/functions.sh

        echo "# ParallelDownloads = 8"
        sudo sed -i '/Architecture/{p;s/.*/ParallelDownloads = 8/;}' /usr/share/manjaro-arm-tools/lib/pacman.conf.aarch64

        echo "# Add BigLinux Repo"
        if [ "${{ inputs.bigbranch }}" = "development" ]; then
          echo '
          [biglinux-testing]
          SigLevel = Optional TrustAll
          Server = https://repo.biglinux.com.br/testing/$arch

          [biglinux-stable]
          SigLevel = Optional TrustAll
          Server = https://repo.biglinux.com.br/stable/$arch' | sudo tee -a /usr/share/manjaro-arm-tools/lib/pacman.conf

          # Copy pacman.conf to rootfs
          sed -i '/bsdtar -xpf $ROOTFS_IMG\/BigLinux-ARM-$ARCH-latest.tar.gz -C $ROOTFS_IMG\/rootfs_$ARCH/{p;s/.*/sudo cp -a $LIBDIR\/pacman.conf $CHROOTDIR\/etc\/pacman.conf/;}' /usr/share/manjaro-arm-tools/lib/functions.sh

          # Change to fast compress
          sed -i '/--threads=0 /s/--threads=0/--threads=0 --fast/' /usr/share/manjaro-arm-tools/lib/functions.sh
        fi

    - name: Checkout ARM Profiles
      shell: bash
      env:
        REPO: ${{ inputs.arm-profiles-repo }}
      run: |
        sudo git clone --depth 1 ${REPO} arm-profiles

    - name: Setup TMATE Session
      uses: mxschmitt/action-tmate@v3
      if: "${{ inputs.tmate == 'true' }}"

    - id: build
      shell: bash
      env:
        DEVICE: ${{ inputs.device }}
        EDITION: ${{ inputs.edition }}
        BRANCH: ${{ inputs.branch }}
        VERSION: ${{ inputs.version }}
        IMGTYPE: ${{ inputs.imgtype }}
      run: |
        [ "$IMGTYPE" != "factory" ] && unset IMGTYPE
        sudo mv -v $GITHUB_WORKSPACE/arm-profiles /usr/share/manjaro-arm-tools/profiles
        if [ -z ${{ inputs.overlay-repo }} ]; then 
          sudo buildarmimg -d $DEVICE -e $EDITION -v $VERSION -b $BRANCH ${IMGTYPE:+-f}
        else
          sudo buildarmimg -d $DEVICE -e $EDITION -v $VERSION -b $BRANCH -k ${{ inputs.overlay-repo }} ${IMGTYPE:+-f}
        fi

        if [ "${{ inputs.bigbranch }}" = "development" ]; then
          imgName=$(find /var/cache/manjaro-arm-tools/img -type f -name "*.img.*")
          sudo mv "$imgName" "$(sed 's/\./_DEVELOPMENT./' <<< $imgName)"
        fi

        ls -lasih /var/cache/manjaro-arm-tools/img

        FILE_PATH=$(find /var/cache/manjaro-arm-tools/img -type f -name "*.img.xz" -exec stat -c '%Y %n' {} \; | sort -nr | awk 'NR==1 {print $2}')
        cp -v $FILE_PATH .

        sha256sum $(basename $FILE_PATH) > $(basename $FILE_PATH).sha256
        mktorrent -v -a udp://tracker.opentrackr.org:1337 -l 21 -w https://github.com/$GITHUB_REPOSITORY/releases/download/$VERSION/$(basename $FILE_PATH) -o $(basename $FILE_PATH).torrent $(basename $FILE_PATH)

        # Rename pkgs
        echo "Rename pkgs"
        imgNamePkgs=$(find /var/cache/manjaro-arm-tools/img -type f -name "*-pkgs.txt" -exec stat -c '%Y %n' {} \; | sort -nr | awk 'NR==1 {print $2}')
        if [ "${{ inputs.bigbranch }}" = "development" ]; then
          sudo cp "$imgNamePkgs" "$(sed 's/-pkgs.*/_DEVELOPMENT.img.xz.pkgs/' <<< $imgNamePkgs)"
        else
          sudo cp "$imgNamePkgs" "$(sed 's/-pkgs.*/.img.xz.pkgs/' <<< $imgNamePkgs)"
        fi

        FILE_PKG=$(find /var/cache/manjaro-arm-tools/img -type f -name "*.pkgs" -exec stat -c '%Y %n' {} \; | sort -nr | awk 'NR==1 {print $2}')
        cp -v $FILE_PKG .

        echo "Split file"
        zip -j -s 1950m $(basename ${FILE_PATH}.zip) $(basename ${FILE_PATH})

        ls -lasih

        echo "FILE_PATH_ZIP=$(basename ${FILE_PATH}.zip)" >> $GITHUB_ENV
        echo "FILE_PATH_Z01=$(basename ${FILE_PATH}.z01)" >> $GITHUB_ENV
        echo "FILE_PKG=$(basename $FILE_PATH).pkgs" >> $GITHUB_ENV
        echo "FILE_SHA256=$(basename $FILE_PATH).sha256" >> $GITHUB_ENV
        echo "FILE_TORRENT=$(basename $FILE_PATH).torrent" >> $GITHUB_ENV