name: rootfs_build
on:
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: 'with TMATE'
        required: false
        default: false
  schedule:
    - cron: '30 19 * * 5'

concurrency:
  group: ${{ github.repository }}-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release:
    runs-on: ubuntu-22.04
    env:
      PACMAN_VERSION: 6.0.2
      ARCH_INSTALL_SCRIPTS_VERSION: 28

    steps:
      - id: time
        uses: boredland/get-time-action@2.0.0
        with:
          format: 'YYYY-MM-DD'

      - name: Install build dependencies
        shell: bash
        run: |
          set -e  # Fail the script if any command fails
          sudo apt-get update
          sudo apt-get install -y \
            gdisk \
            zip \
            systemd-container \
            bmap-tools \
            asciidoc \
            libarchive-tools \
            git \
            build-essential \
            cmake \
            libarchive-dev \
            pkg-config \
            libcurl4-openssl-dev \
            libgpgme-dev \
            libssl-dev \
            fakeroot \
            dh-autoreconf \
            qemu-utils \
            qemu-efi-aarch64 \
            qemu-system-arm \
            qemu-user-static
          sudo pip3 install meson ninja

      - name: Install pacman
        shell: bash
        run: |
          set -e  # Fail the script if any command fails
          sudo git clone --depth 1 https://gitlab.manjaro.org/packages/core/pacman.git
          pushd pacman
            sudo wget https://sources.archlinux.org/other/pacman/pacman-${{ env.PACMAN_VERSION }}.tar.xz
            sudo tar -xvf pacman-${{ env.PACMAN_VERSION }}.tar.xz
            pushd pacman-${{ env.PACMAN_VERSION }}
              sudo meson --prefix=/usr \
                        --buildtype=plain \
                        -Ddoc=disabled \
                        -Ddoxygen=enabled \
                        -Dscriptlet-shell=/usr/bin/bash \
                        -Dldconfig=/usr/bin/ldconfig \
                        build
              sudo meson compile -C build
              sudo meson install -C build
            popd
            sudo install -m644 pacman.conf /etc/pacman.conf
            sudo install -m644 makepkg.conf /etc/
            sudo mkdir -p /etc/pacman.d
            sudo touch /etc/pacman.d/mirrorlist
          popd

      - name: Setup QEMU binfmt
        shell: bash
        run: |
          set -e  # Fail the script if any command fails
          sudo wget https://gitlab.manjaro.org/packages/community/manjaro-arm-qemu-static/-/raw/master/qemu-static.conf -O /usr/lib/binfmt.d/qemu-static.conf
          sudo service systemd-binfmt restart

      - name: Install arch-install-scripts
        shell: bash
        run: |
          set -e  # Fail the script if any command fails
          sudo wget https://github.com/archlinux/arch-install-scripts/archive/refs/tags/v${{ env.ARCH_INSTALL_SCRIPTS_VERSION }}.tar.gz -O arch-install-scripts.tar.gz
          sudo tar -xvf arch-install-scripts.tar.gz
          sudo make -C arch-install-scripts-${{ env.ARCH_INSTALL_SCRIPTS_VERSION }}
          sudo make -C arch-install-scripts-${{ env.ARCH_INSTALL_SCRIPTS_VERSION }} check
          sudo make -C arch-install-scripts-${{ env.ARCH_INSTALL_SCRIPTS_VERSION }} PREFIX=/usr install

      - name: Install biglinux-arm-tools
        shell: bash
        run: |
          set -e  # Fail the script if any command fails
          sudo git clone https://github.com/jdorigao/biglinux-arm-tools.git
          install_m_a_tools() {
              pkgname=biglinux-arm-tools
              sudo install -dm777 /usr/share/$pkgname/lib
              sudo install -dm777 /usr/share/$pkgname/profiles
              sudo install -d /etc/$pkgname/
              sudo install -dm777 /var/lib/$pkgname/{pkg,img,tmp,profiles}
              sudo install -dm777 /var/cache/$pkgname/{pkg/pkg-cache,img}
              sudo install -Dm755 $pkgname/lib/* /usr/share/$pkgname/lib/
              sudo install -Dm755 $pkgname/bin/* /usr/bin/
              sudo install -Dm755 $pkgname/lib/biglinux-arm-tools.conf /etc/biglinux-arm-tools/
          }
          install_m_a_tools

          sudo sed -i -e 's|1>/dev/null||g' /usr/share/biglinux-arm-tools/lib/functions.sh
          sudo sed -i -e 's|1> /dev/null 2>&1||g' /usr/share/biglinux-arm-tools/lib/functions.sh
          sudo sed -i -e 's|2>/dev/null||g' /usr/share/biglinux-arm-tools/lib/functions.sh

          # Remover compress e gerar rootfs
          sudo sed -i ':a;$!{N;ba;};s/\(.*\)compress_rootfs/\1/' /usr/bin/buildrootfs

      - name: Tmate
        uses: mxschmitt/action-tmate@v3
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}

      - name: Build rootfs
        shell: bash
        run: |
          set -e  # Fail the script if any command fails
          sudo buildrootfs

          ls -lasih /var/cache/biglinux-arm-tools/img

          FILE_PATH=$(find /var/cache/biglinux-arm-tools/img -type f -name "*.tar.gz" -exec stat -c '%Y %n' {} \; | sort -nr | awk 'NR==1 {print $2}')
          cp -v $FILE_PATH .

          echo "FILE_PATH=$(basename $FILE_PATH)" >> $GITHUB_ENV

      - name: Release assets
        uses: softprops/action-gh-release@v0.1.15
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.time.outputs.time }}
          name: rootfs ${{ steps.time.outputs.time }}
          draft: false
          prerelease: false
          files: |
            ${{ env.FILE_PATH }}

      - name: Clean up
        shell: bash
        run: |
          set -e  # Fail the script if any command fails
          sudo rm -rf pacman arch-install-scripts-* arch-install-scripts.tar.gz biglinux-arm-tools