name: rootfs_build
on:
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: 'with TMATE'
        required: false
        default: false
  schedule:
    - cron:  '30 19 * * 5'

concurrency:
  group: ${{ github.repository }}-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release:
    runs-on: ubuntu-22.04
    steps:
      - id: time
        uses: boredland/get-time-action@2.0.0
        with:
          format: 'YYYY-MM-DD'
          
      - name: install-build-dependencies
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-fast install -y \
            gdisk \
            zip \
            systemd-container \
            bmap-tools asciidoc \
            libarchive-tools \
            git \
            build-essential \
            cmake \
            libarchive-dev \
            pkg-config \
            libcurl4-openssl-dev \
            libgpgme-dev \
            libssl-dev \
            fakeroot \
            dh-autoreconf \
            qemu-utils \
            qemu-efi-aarch64 \
            qemu-system-arm \
            qemu-user-static
          sudo pip3 install meson
          sudo pip3 install ninja
          
      - name: install-pacman
        shell: bash
        env:
          PACMAN_VERSION: 6.0.2
        run: |
          sudo git clone --depth 1 https://gitlab.manjaro.org/packages/core/pacman.git
          pushd pacman
            sudo wget https://sources.archlinux.org/other/pacman/pacman-${PACMAN_VERSION}.tar.xz
            sudo tar -xvf pacman-${PACMAN_VERSION}.tar.xz
            pushd pacman-${PACMAN_VERSION}
              sudo patch -p1 -i ../pacman-sync-first-option.patch
              sudo meson --prefix=/usr \
                        --buildtype=plain \
                        -Ddoc=disabled \
                        -Ddoxygen=enabled \
                        -Dscriptlet-shell=/usr/bin/bash \
                        -Dldconfig=/usr/bin/ldconfig \
                        build
              sudo meson compile -C build
              sudo meson install -C build
            popd
            sudo install -m644 pacman.conf /etc/pacman.conf
            sudo install -m644 makepkg.conf /etc/
            sudo mkdir -p /etc/pacman.d
            sudo touch /etc/pacman.d/mirrorlist
          popd
          
          sudo rm -r pacman
          
      - name: setup-qemu-binfmt
        shell: bash
        run: |
          sudo wget https://gitlab.manjaro.org/packages/community/manjaro-arm-qemu-static/-/raw/master/qemu-static.conf -O /usr/lib/binfmt.d/qemu-static.conf
          sudo service systemd-binfmt restart 
          
      - name: install-arch-install-scripts
        shell: bash
        env:
          VERSION: 28
        run: |
          sudo wget https://github.com/archlinux/arch-install-scripts/archive/refs/tags/v${VERSION}.tar.gz -O arch-install-scripts.tar.gz
          sudo tar -xvf arch-install-scripts.tar.gz
          sudo make -C arch-install-scripts-${VERSION}
          sudo make -C arch-install-scripts-${VERSION} check
          sudo make -C arch-install-scripts-${VERSION} PREFIX=/usr install
          
          sudo rm arch-install-scripts.tar.gz 
          sudo rm -r arch-install-scripts-${VERSION}         
          
      - name: install-manjaro-arm-tools
        shell: bash
        run: |
          sudo git clone https://gitlab.manjaro.org/manjaro-arm/applications/manjaro-arm-tools.git
          install_m_a_tools() {
              pkgname=manjaro-arm-tools
              sudo install -dm777 /usr/share/$pkgname/lib
              sudo install -dm777 /usr/share/$pkgname/profiles
              sudo install -d /etc/$pkgname/
              sudo install -dm777 /var/lib/$pkgname/{pkg,img,tmp,profiles}
              sudo install -dm777 /var/cache/$pkgname/{pkg/pkg-cache,img}
              sudo install -Dm755 $pkgname/lib/* /usr/share/$pkgname/lib/
              sudo install -Dm755 $pkgname/bin/* /usr/bin/
              sudo install -Dm755 $pkgname/lib/manjaro-arm-tools.conf /etc/manjaro-arm-tools/
          }
          install_m_a_tools
          
          sudo sed -i -e 's|1>/dev/null||g' /usr/share/manjaro-arm-tools/lib/functions.sh   
          sudo sed -i -e 's|1> /dev/null 2>&1||g' /usr/share/manjaro-arm-tools/lib/functions.sh
          sudo sed -i -e 's|2>/dev/null||g' /usr/share/manjaro-arm-tools/lib/functions.sh
          
          sudo rm -r manjaro-arm-tools
          
      - name: BigLinux-changes
        shell: bash
        run: |
          # BigLinux Information
          sudo sed -i 's|^Manjaro Linux|BigLinux, based in Manjaro Linux|g' $BUILDDIR/$ARCH/etc/issue
          sudo sed -i 's|^ *\bNAME\b *=.*|NAME="BigLinux based in Manjaro Linux"|;s|^ *\ID\b *=.*|ID="biglinux-arm"|;s|^ *\ID_LIKE\b *=.*|ID_LIKE="biglinux arch"|;s|^ *\bPRETTY_NAME\b *=.*|PRETTY_NAME="BigLinux based in Manjaro Linux"|;s|^ *\ANSI_COLOR\b *=.*|ANSI_COLOR="32;1;24;144;200"|;s|^ *\bHOME_URL\b *=.*|HOME_URL="https://www.biglinux.com.br"|;s|^ *\bSUPPORT_URL\b *=.*|SUPPORT_URL="https://forum.biglinux.com.br"|;s|^ *\LOGO\b *=.*|LOGO="biglinux-blue"|' $BUILDDIR/$ARCH/usr/lib/os-release
          sudo sed -i 's|^ *\bDISTRIB_ID\b *=.*|DISTRIB_ID="BigLinux based in Manjaro Linux"|g;s|^ *\bDISTRIB_DESCRIPTION\b *=.*|DISTRIB_DESCRIPTION="BigLinux"|g' $BUILDDIR/$ARCH/usr/lib/os-release

          # Change name on login
          echo 'Welcome to BigLinux ARM
          ~~Website:  https://www.biglinux.com.br
          ~~Forum:    https://forum.biglinux.com.br
          ~~Telegram: https://t.me/BigLinuxCommunity' | sudo tee $BUILDDIR/$ARCH/etc/motd

          echo '
          [biglinux-testing]
          SigLevel = Optional TrustAll
          Server = https://repo.biglinux.com.br/testing/aarch64
        
          [biglinux-stable]
          SigLevel = Optional TrustAll
          Server = https://repo.biglinux.com.br/stable/aarch64' | sudo tee -a /usr/share/manjaro-arm-tools/lib/pacman.conf.aarch64

          # Name imagen
          sudo sed -i 's/Manjaro-ARM-$ARCH/BigLinux-ARM-$ARCH/g' /usr/bin/buildrootfs
          
      - name: Tmate
        uses: mxschmitt/action-tmate@v3
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}
          
      - name: build-rootfs
        shell: bash
        run: |
          sudo buildrootfs
                            
          ls -lasih /var/cache/manjaro-arm-tools/img
          
          FILE_PATH=$(find /var/cache/manjaro-arm-tools/img -type f -name "*.tar.gz" -exec stat -c '%Y %n' {} \; | sort -nr | awk 'NR==1 {print $2}')
          cp -v $FILE_PATH .

          echo "FILE_PATH=$(basename $FILE_PATH)" >> $GITHUB_ENV
          
      - name: release-assets
        uses: softprops/action-gh-release@v0.1.15
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.time.outputs.time }}
          name: ${{ steps.time.outputs.time }}
          draft: false
          prerelease: false
          files: |
            ${{ env.FILE_PATH }}            
          
