name: Rasp 3/4 Matrix Development
on:
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: 'with TMATE'
        required: false
        default: false

concurrency:
  group: ${{ github.repository }}-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        IMG-NAME: [BigLinux]
        DEVICE: [rpi4,generic]
        # EDITION: [gnome,kde-plasma,mate,minimal,sway,xfce]
        # EDITION: [kde-plasma,minimal,iot]
        EDITION: [kde-plasma]
        BRANCH: [stable]
        BIGBRANCH: [development]
    steps:
      - id: time
        name: Release
        uses: boredland/get-time-action@2.0.0
        with:
          format: 'YYYY-MM-DD_HH-mm'
          
      - id: name
        name: Name
        shell: bash
        run: |
          echo "name=$(echo ${{ matrix.img-name }} | sed -e 's/\(.*\)/\L\1/')" >> $GITHUB_OUTPUT
          echo ${{ github.repository }}-${{ github.workflow }}-${{ github.ref }}
          echo "Tmate = ${{ inputs.debug_enabled }}"
          
      - id: image-build
        name: Image Build
        uses: BigLinux-Package-Build/build-iso-arm@main
        with:
          img-name: ${{ matrix.img-name }}
          name: ${{ steps.name.outputs.name }}
          device: ${{ matrix.device }}
          edition: ${{ matrix.edition }}
          branch: ${{ matrix.branch }}
          bigbranch: ${{ matrix.bigbranch }}
          version: ${{ steps.time.outputs.time }}
          tmate: ${{ inputs.debug_enabled }}
          
      - name: Release Upload
        uses: softprops/action-gh-release@v0.1.15
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.time.outputs.time }}
          name: BigLinux ARM ${{ steps.time.outputs.time }}
          draft: false
          prerelease: false
          files: |
            ${{ env.FILE_PATH_ZIP }}
            ${{ env.FILE_PATH_Z01 }}
            ${{ env.FILE_PKG }}
            ${{ env.FILE_SHA256 }}
            ${{ env.FILE_TORRENT }}
            
      - name: Tmate if failure
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3
